### ISSUE TITLE
Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!

### ISSUE THREAD

**Issue by hirenicestone** [RexanWONG/text-behind-image#20]
⨯ node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.10.0_@supabase+supabase-js@2.46.1/node_modules/@supabase/auth-helpers-nextjs/dist/index.js (47:1) @ createClientComponentClient
 ⨯ Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
    at SupabaseProvider.useState (./providers/SupabaseProvider.tsx:19:132)
    at SupabaseProvider (./providers/SupabaseProvider.tsx:18:77)
digest: "2006963411"
  45 | } = {}) {
  46 |   if (!supabaseUrl || !supabaseKey) {
> 47 |     throw new Error(
     | ^
  48 |       "either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!"
  49 |     );
  50 |   }
 GET / 500 in 333ms
 GET /favicon.ico 200 in 57ms
 GET /favicon.ico 200 in 20ms
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies

I got above error while running code in my local machine
Thanks

**Comment by shiv19** [comment]
The tool works locally if you remove the requirement for user and supabase and bypass authentication.

**Comment by hirenicestone** [comment]
Thanks:)

**Comment by ladypiapia** [comment]
Same question! Which part should I comment to bypass authentication? I'm junior,Thank you so much!

**Comment by KrishnaCodez** [comment]
To bypass authentication, you can modify the following line in 

**app/app/page.tsx**

Comment out or remove this validation checks:
{user && session && session.user and Authenticate component. 

By removing or commenting out this line, the authentication requirement will be bypassed locally.

**Comment by RoversX** [comment]
I made a cleaner and more static version at https://github.com/RoversX/text-behind-image-mini. It's a fork of the original text-behind-image project, and fully preserve the original AGPL-3.0 license.
